apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsentry-backend
  namespace: appsentry
  labels:
    app: appsentry-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appsentry-backend
  template:
    metadata:
      labels:
        app: appsentry-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: docker.io/lijomadassery/appsentry-backend:master
        ports:
        - containerPort: 3001
          name: http
        env:
        # Kubernetes Downward API - Pod Metadata
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_CONTAINER_NAME
          value: "backend"
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: K8S_CLUSTER_NAME
          value: "appsentry-cluster"
        
        # Application Configuration
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: CORS_ORIGIN
          value: "*"
        - name: LOG_LEVEL
          value: "info"
        
        # Database Configuration
        - name: DATABASE_URL
          value: "mysql://appsentry:appsentry456@mysql.appsentry.svc.cluster.local:3306/appsentry"
        
        # ClickHouse Configuration
        - name: CLICKHOUSE_HOST
          value: "clickhouse.appsentry-otel.svc.cluster.local"
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: CLICKHOUSE_DATABASE
          value: "otel"
        - name: CLICKHOUSE_USERNAME
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          value: ""
        
        # OTEL Configuration
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        - name: OTEL_SERVICE_NAME
          value: "AppSentry Backend"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.0"
        
        # JWT Authentication Configuration
        - name: JWT_SECRET
          value: "appsentry-jwt-secret-2025-dev-cluster"
        - name: JWT_EXPIRES_IN
          value: "1h"
        - name: JWT_REFRESH_EXPIRES_IN
          value: "7d"
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: appsentry-backend
  namespace: appsentry
  labels:
    app: appsentry-backend
spec:
  selector:
    app: appsentry-backend
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP