apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: appsentry
type: Opaque
data:
  # root password: 'appsentry123' (base64 encoded)
  mysql-root-password: YXBwc2VudHJ5MTIz
  # app password: 'appsentry456' (base64 encoded)  
  mysql-password: YXBwc2VudHJ5NDU2

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: appsentry
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS appsentry;
    CREATE USER IF NOT EXISTS 'appsentry'@'%' IDENTIFIED BY 'appsentry456';
    GRANT ALL PRIVILEGES ON appsentry.* TO 'appsentry'@'%';
    FLUSH PRIVILEGES;

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: appsentry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: appsentry
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "appsentry"
        - name: MYSQL_USER
          value: "appsentry"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -u
            - root
            - -p$MYSQL_ROOT_PASSWORD
            - -e
            - "SELECT 1"
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init
        configMap:
          name: mysql-config

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: appsentry
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP