apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = false
    
    [grafana_net]
    url = https://grafana.net
    
    [log]
    mode = console
    
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
    [server]
    root_url = http://localhost/grafana/
    serve_from_sub_path = true
    domain = localhost
    
    [dataproxy]
    timeout = 30
    keep_alive_seconds = 30
    
    [database]
    max_open_conn = 20
    max_idle_conn = 10
    conn_max_lifetime = 14400
    
    [plugin.grafana-clickhouse-datasource]
    sql_datasource_max_open_conns_default = 100
    sql_datasource_max_idle_conns_default = 10
    sql_datasource_conn_max_lifetime_default = 14400

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: ClickHouse
        type: vertamedia-clickhouse-datasource
        uid: clickhouse
        access: proxy
        url: http://clickhouse.appsentry-otel.svc.cluster.local:8123
        database: otel
        basicAuth: false
        isDefault: true
        jsonData:
          defaultDatabase: otel
          port: 8123
          server: clickhouse.appsentry-otel.svc.cluster.local
          username: default
        secureJsonData:
          password: ""
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'AppSentry'
        orgId: 1
        folder: 'AppSentry'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards