name: Fast Development Build

on:
  push:
    branches: [ develop, feature/* ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io

jobs:
  build-backend-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image (dev)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/appsentry-backend:${{ github.ref_name }}
          ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/appsentry-backend:dev
        platforms: linux/amd64  # Single platform for speed
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

  build-frontend-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend image (dev)
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/appsentry-frontend:${{ github.ref_name }}
          ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/appsentry-frontend:dev
        platforms: linux/amd64  # Single platform for speed
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

  summary:
    runs-on: ubuntu-latest
    needs: [build-backend-dev, build-frontend-dev]
    steps:
    - name: Development build summary
      run: |
        echo "🚀 Fast development build completed!"
        echo "📦 Images built:"
        echo "  - Backend: ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/appsentry-backend:${{ github.ref_name }}"
        echo "  - Frontend: ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/appsentry-frontend:${{ github.ref_name }}"
        echo "⚡ Optimizations applied:"
        echo "  - Single platform build (linux/amd64)"
        echo "  - GitHub Actions cache enabled"
        echo "  - Optimized Docker layers"
        echo "  - No security scanning for speed"